ss-rust: switch to nightly toolchain
reference: https://github.com/pexcn/docker-images/runs/7296406264
error[E0554]: `#![feature]` may not be used on the stable release channel